### DISCUSSION TITLE
Replacement for homebrew_cask?

### DISCUSSION THREAD

**Discussion by maspotts** [geerlingguy/ansible-collection-mac#105] [Q&A]
I have an old playbook with lots of roles, which I want to use again to set up a new macbook, but it seems that the homebrew_cask directive no longer works (actually just hangs), eg:

```
- name: Install some commonly used casks
  homebrew_cask:
    name:
      - google-chrome
      - firefox
```

I see I could define homebrew_cask_apps; but do I need to do that instead (and once for each role)?  Apologies if this should be obvious, but I'm still learning ansible!
