### ISSUE TITLE
Problems with the PATH fo mas commands

### ISSUE THREAD

**Issue by toby-griffiths** [geerlingguy/ansible-collection-mac#10]
Hi there,

I'm running the mac-dev-setup playbook on a remote machine, and it's failing on the `mas account` task, as follows…

```
TASK [geerlingguy.mac.mas : Get MAS account status] **************************************************************************************
task path: /Users/toby/.ansible/collections/ansible_collections/geerlingguy/mac/roles/mas/tasks/main.yml:5
fatal: [marvin]: FAILED! => changed=false
  cmd: mas account
  failed_when_result: true
  msg: '[Errno 2] No such file or directory'
  rc: 2
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

I can run `mas` on the command line when logged in locally to the machine, without the full path, since `/usr/local/bin` is in my `$PATH`.

I've added a debug step to dump out the `$PATH` when using ansible and it seems to be missing `/usr/local/bin` for some reason…

```
TASK [geerlingguy.mac.mas : Debug mas cmd part 1] ****************************************************************************************
task path: /Users/toby/.ansible/collections/ansible_collections/geerlingguy/mac/roles/mas/tasks/main.yml:5
changed: [marvin] => changed=true
  cmd:
  - echo
  - $PATH
  delta: '0:00:00.002861'
  end: '2021-06-25 20:38:35.642596'
  rc: 0
  start: '2021-06-25 20:38:35.639735'
  stderr: ''
  stderr_lines: <omitted>
  stdout: /usr/bin:/bin:/usr/sbin:/sbin
  stdout_lines: <omitted>
```

What's the best way to fix this?  I can submit a PR, but where should I be adding `/usr/local/bin` to the PATH?  For all users (`/etc/profile`) or to just the current users, perhaps?
