### ISSUE TITLE
How do I specify the formula, if the same package exists as both formula and cask?

### ISSUE THREAD

**Issue by maspotts** [geerlingguy/ansible-collection-mac#109]
If a formula and cask exist with the same name, then I can install the cask using `homebrew_cask` but trying to install the formula (with `homebrew`) results in an error message: ```fatal: [ponyo]: FAILED! => {"changed": false, "msg": "Warning: Treating foo as a formula. For the cask, use homebrew/cask/foo or specify the `--cask` flag."}```.  I don't see any way to force the formula to install: are you thinking of adding `homebrew_formula` for this use case?  Or am I missing something?  Thanks!

**Comment by cmmarslender** [comment]
Seems like allowing passing through the `force_formula: true` option to the community homebrew module would enable solving this. I'm hitting this error with docker and cmake currently with no way to easily work around it

**Comment by sinkr** [comment]
Same here and it's pretty hard to resolve if Homebrew sees both a cask and a formula available, like `fontforge`.

This seems to be the crux of determining if you have an issue (packages available as taps and casks):
```
$ brew search fontforge                                                                       
==> Formulae
fontforge ✔                                                                 fontconfig ✔

==> Casks
font-firge          font-forum            font-ole             font-rye            fontforge

```

**Comment by sinkr** [comment]
I came up with a fairly non-invasive way to do this in the `play.yml` without relying on modifying the upstream module.  I was unable to use the `homebrew:` method(?) because it simply was not set up to be overridden, so in this case I shell directly and invoke `brew` outside of any other modules. 

Add this to your `tasks:` section:
```
  tasks:
(...)

    - name: Ensure Homebrew formula packages are installed with --formula
      shell: "{{ homebrew_brew_bin_path }}/brew install --formula {{ item }}"
      loop: "{{ homebrew_formula_forced_installed_packages }}"
      register: result
      ignore_errors: no
      changed_when: "'already installed' not in result.stdout"
      failed_when: "'Warning:' not in result.stderr"
      tags:
        - homebrew_formula_force
```

Add this somewhere about your `vars:` section:
```
    homebrew_formula_forced_installed_packages:
      - fontforge
```

Kinda hacky, but everything about Ansible feels pretty hacky after living in Terraform + Kubernetes for years.
