### ISSUE TITLE
Problem with PATH for hombrew_tap

### ISSUE THREAD

**Issue by spyesx** [geerlingguy/ansible-collection-mac#17]
Hi,

I have a fresh install of Big Sur on a Mac Mini (M1) and I run this role remotely from an Ansible 2.9. Unfortunately it fails at `[homebrew : Ensure configured taps are tapped]`.

```
TASK [homebrew : Ensure configured taps are tapped] ****************************************************************************************************************
failed: [loxodon] (item={u'url': u'https://github.com/Homebrew/homebrew-core.git', u'name': u'homebrew/core'}) => changed=false
  ansible_loop_var: item
  item:
    name: homebrew/core
    url: https://github.com/Homebrew/homebrew-core.git
  msg: 'Failed to find required executable brew in paths: /usr/bin:/bin:/usr/sbin:/sbin'
failed: [loxodon] (item={u'url': u'https://github.com/Homebrew/homebrew-cask.git', u'name': u'homebrew/cask'}) => changed=false
  ansible_loop_var: item
  item:
    name: homebrew/cask
    url: https://github.com/Homebrew/homebrew-cask.git
  msg: 'Failed to find required executable brew in paths: /usr/bin:/bin:/usr/sbin:/sbin'
```

I've added `/opt/homebrew/bin` to my PATH in `.zshrc` and `.bash_profile` just in case

```
% echo 'export PATH="$PATH:/opt/homebrew/bin"' >> ~/.zshrc
% echo 'export PATH="$PATH:/opt/homebrew/bin"' >> ~/.bash_profile
```
Now my user's PATH looks like:

```
nico@loxodon ~ % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin
```

And `root`'s PATH is 

```
loxodon:~ root# echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Did I miss something?

**Comment by geerlingguy** [comment]
When you're logged into that mac, and run `which brew`, where is that located?

**Comment by spyesx** [comment]
Hi :)

I have that

```
% which brew
/opt/homebrew/bin/brew
```

**Comment by spyesx** [comment]
Well, apparently that worked but I'm not sure with changing `/usr/local/bin` ownership.

```yaml
- name: Check if homebrew binary is already in /usr/local/bin
  stat: "path=/usr/local/bin/brew"
  register: homebrew_binary_usr_bin
  check_mode: false

- name: Symlink brew to /usr/local/bin
  file:
    src: "{{ homebrew_install_path }}/bin/brew"
    dest: "/usr/local/bin/brew"
    state: link
  when: not homebrew_binary_usr_bin.stat.exists
  become: true

- name: Set /usr/local/bin ownership
  command: "chown -R {{ homebrew_user }} /usr/local/bin"
  when: not homebrew_binary_usr_bin.stat.exists
  become: true
```
