### ISSUE TITLE
Homebrew Role: custom taps stall out

### ISSUE THREAD

**Issue by ahgraber** [geerlingguy/ansible-collection-mac#25]
If I try to include custom taps, the role progresses until the package/formulae install that requires the custom tap, and then stalls with no warning or error.  Maybe I'm not referencing the tapped formula correctly?

Trivial configuration:

```yaml
# homebrew_install_path: /usr/local/homebrew
homebrew_installed_packages:
  - autoconf
  - automake
  # appears to freeze during "automake" but it is the `msodbcsql17` formula that freezes;
  # if I rerun, both `autoconf` and `automake` register as installed and it still stalls here
  - msodbcsql17  # requires tap

homebrew_taps:
  - homebrew/cask
  - homebrew/cask-versions
  - name: microsoft/mssql-release
    url: 'https://github.com/Microsoft/homebrew-mssql-release'

```
