### ISSUE TITLE
Failed to find required executable brew in paths

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/ansible-collection-mac#27]
Got a mac Mini with M1 chip and `geerlingguy.mac.homebrew` role that works great on my Intel mac fails on my M1 mac.

Playbook called macos_workstation.yml
```yaml
- name: macOS Workstation Playbook
  hosts: all

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    homebrew_installed_packages:
      - git
    homebrew_taps:
      - homebrew/core
    homebrew_cask_apps:
      - powershell

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
```
Ansible run
```
$ ansible-playbook -i testing  --limit="macmini" -K ../macos_workstation.yml
```
Error
```
TASK [geerlingguy.mac.homebrew : Install configured cask applications.] ********
failed: [macmini] (item=powershell) => {"ansible_loop_var": "item", "changed": false, "item": "powershell", "msg": "Failed to find required executable brew in paths: /usr/bin:/bin:/usr/sbin:/sbin"}
```
The [defaults](https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/defaults/main.yml) set
```yaml
homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"
```
Does the `homebrew_cask` look into the `homebrew_brew_bin_path`?
```
    - name: Install configured cask applications.
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
        accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
        sudo_password: "{{ ansible_become_password | default(omit) }}"
      loop: "{{ homebrew_cask_apps }}"
      notify:
        - Clear homebrew cache
```
Seems like `homebrew_cask` does not follow the `homebrew_brew_bin_path`. Changed playbook, addd a pre-task
```yaml
  pre_tasks:
    - debug:
        msg: "{{ homebrew_brew_bin_path }}"
```
Ansible shows  `homebrew_brew_bin_path` correct.
```
TASK [debug] *******************************************************************
ok: [macmini.castle.real-time.com] => {
    "msg": "/opt/homebrew/bin"
}
```
```
% file /opt/homebrew/bin/brew
/opt/homebrew/bin/brew: Bourne-Again shell script text executable, ASCII text

% /opt/homebrew/bin/brew --version
Homebrew 3.3.4
Homebrew/homebrew-core (git revision e2dbff3dad5; last commit 2021-11-16)
```
Do I need to apply a work-around like in #10 ?
```
% echo $SHELL
/bin/zsh
```
```
% sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```
```
% python3 -V
Python 3.8.9
```
```
$ ansible --version
ansible 2.9.16.post0
```

**Comment by basictheprogram** [comment]
Changed my shell to base
```
chsh -s /bin/bash
```
Updated my PATH in ~/.bash_profle
```
PATH="${HOME}/bin:/opt/homebrew/bin:${PATH}"
export PATH
```
And
```
$ which brew
/opt/homebrew/bin/brew
```
But Ansible still throws an error
```
TASK [geerlingguy.mac.homebrew : Install configured cask applications.] ********
failed: [macmini] (item=powershell) => {"ansible_loop_var": "item", "changed": false, "item": "powershell", "msg": "Failed to find required executable brew in paths: /usr/bin:/bin:/usr/sbin:/sbin"}
```
It doesn't look like `homebrew_cask` honors the users PATH

**Comment by basictheprogram** [comment]
The [docs](https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_cask_module.html#ansible-collections-community-general-homebrew-cask-module) say [path](https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_cask_module.html#parameter-path) defaults to `"/usr/local/bin:/opt/homebrew/bin"`

In [main.yml](https://github.com/geerlingguy/ansible-collection-mac/blob/master/roles/homebrew/tasks/main.yml) I changed `homebrew_cask` to `community.general.homebrew_cask` 
```yaml
    - name: Install configured cask applications.
      community.general.homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
        accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
        sudo_password: "{{ ansible_become_password | default(omit) }}"
      loop: "{{ homebrew_cask_apps }}"
      notify:
        - Clear homebrew cache
 ```
And this seems to fix my problem. 

I think the problem is my version of ansible (ansible 2.9.16.post0) and it's using the `/src/ansible/lib/ansible/modules/packaging/os/homebrew_cask.py` and not the `community.general.homebrew_cask` collection.
