### ISSUE TITLE
dockutil is not on ssh path

### ISSUE THREAD

**Issue by johnlane** [geerlingguy/ansible-collection-mac#29]
Recently found your 101 series, I'm trying out your dock role. I have a problem where the dock tasks fail with errors like this
```
FAILED! => {"msg": "The conditional check '\"No such file or directory\" in dockitem_exists.stdout or \"command not found\" in dockitem_exists.stdout\n' failed. The error was: error while evaluating conditional (\"No such file or directory\" in dockitem_exists.stdout or \"command not found\" in dockitem_exists.stdout\n): 'dict object' has no attribute 'stdout'"}
```
The reason there is no `stdout` is because the command `dockutil` cannot be found. The reason for that is because the path exposed by the ssh server on macos does not include `/usr/local/bin` which is where Homebrew installed dockutil. SSH also has by default `PermitUserEnvironment` set to `no`. 

The SSH man page suggests the path it exposes is a compile-time option. You can see it like this
```
ssh me@mymac.example.com env
..
PATH=/usr/bin:/bin:/usr/sbin:/sbin
..
```

A fix that worked for me is to prefix `dockutil` with the full path `/usr/local/bin/dockutil` in all of the task files. However I am suprised you haven't hit this so suspect there is something I'm missing?
I've tried a couple of available macs here, one mojave and another catalina one. My Ansible client is running on Linux and is 2.10.4. The version of your collection is 1.4.0.

**Comment by jamesmarble** [comment]
I ran into this with both `geerlingguy.mac.dock` not having `dockutil` on the path and `geerlingguy.mac.mas` not having `mas` on the path when running on a remote mac. My work-around is to add the location that Homebrew installs those tools on my machine to the `PATH` when I call the roles. Something like:

```yml
    - role: geerlingguy.mac.mas
      environment:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin'
    - role: geerlingguy.mac.dock
      environment:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin'
```
