### ISSUE TITLE
couldn't resolve module/action 'homebrew_cask'

### ISSUE THREAD

**Issue by phumpal** [geerlingguy/ansible-collection-mac#35]
Trying to update to the new role (iow: coming from [geerlinguy.homebrew](https://github.com/geerlingguy/ansible-role-homebrew))

```shell
ERROR! couldn't resolve module/action 'homebrew_cask'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '~/.ansible/collections/ansible_collections/geerlingguy/mac/roles/homebrew/tasks/main.yml': line 119, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Cask.
    - name: Ensure blacklisted cask applications are not installed.
      ^ here
```

roles include like so

```yaml
    roles:
      - geerlingguy.mac.homebrew
      - geerlingguy.mac.mas
      - geerlingguy.mac.dock
```

and requirements
```yaml
---
roles:
  - name: elliotweiser.osx-command-line-tools

collections:
  - name: geerlingguy.mac
```
