### ISSUE TITLE
Any ideas how to implement brew services?

### ISSUE THREAD

**Issue by Markus-** [geerlingguy/ansible-collection-mac#39]
I am new to homebrew and just learned about the services feature, which handles the launchd stuff.

I would just install the packages with setting hombrew_installed_packages and put the rest in post tasks and handlers. 
Do you have any ideas how to use this role with "brew services" in another way?

Regards
Markus

**Comment by buluma** [comment]
tried https://github.com/geerlingguy/ansible-role-homebrew?

**Comment by Markus-** [comment]
I think there is nothing about services.

I want to control "brew servcies ..."

**Comment by lotyp** [comment]
> I think there is nothing about services.
> 
> I want to control "brew servcies ..."

Example:
```
- name: Dnsmasq | Restarting Dnsmasq Service
  community.general.launchd:
    name: homebrew.mxcl.dnsmasq
    state: restarted
  listen: Restart Dnsmasq
  become: true
```
