### ISSUE TITLE
`mac.homebrew`: Install `mas` apps from Brewfile over SSH does not work

### ISSUE THREAD

**Issue by tuxpeople** [geerlingguy/ansible-collection-mac#40]
I'd like to reopen https://github.com/geerlingguy/ansible-role-homebrew/issues/146 here, as the issue still exists.

I have a Brewfile with multiple `mas` apps in it. When I run the playbook over SSH, it fails:

```sh
TASK [geerlingguy.mac.homebrew : Install from Brewfile.] *******************************************************************************************************************************************************************************************************************************************************************
fatal: [ws547]: FAILED! => changed=true
  cmd:
  - /usr/local/bin/brew
  - bundle
  delta: '0:00:09.632515'
  end: '2022-04-01 15:18:18.952991'
  msg: non-zero return code
  rc: 1
  start: '2022-04-01 15:18:09.320476'
  stderr: 'Error: Unable to install Affinity Designer app. mas installation failed.'
  stderr_lines: <omitted>
  stdout: 
(Lot of Brewfile content)
  stdout_lines: <omitted>
```

However, it works using `ansible_connection=local` therefor I'm using this workaround now:

```
- name: Set controller_host fact
  set_fact:
    controller_host: "{{lookup('pipe','hostname')}}"

- name: Switch to local connection if this is the device
  set_fact:
    ansible_connection: local
  when: ansible_hostname == controller_host
```
