### ISSUE TITLE
Application doesn't get added to dock if it's in your recent items

### ISSUE THREAD

**Issue by Maddog2050** [geerlingguy/ansible-collection-mac#54]
If you have recent applications turned on for the dock and the application is in your recent applications the application doesn't get added to the persistent applications on the dock.

To reproduce this error:

1. Enable recent applications for the dock
2. Close the application
3. Open the application so that it's in your recent applications
4. Have the application specified in the dockitems_persist list (example below)
5. Run the dock role (The app is not added to the persistent dock)

```yaml
dockitems_persist:
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 5
```
