### ISSUE TITLE
Error: The following directories are not writable by your user:\n/opt/homebrew

### ISSUE THREAD

**Issue by thomascrowley** [geerlingguy/ansible-collection-mac#71]
I am getting an error when trying to use the homebrew role

My playbook.yml contains the following

```yaml
---
- hosts: localhost
  become: no
  connection: local

  vars_files:
    - secrets.yml
  vars:
    homebrew_installed_packages:
      - mysql

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.homebrew
 ```

Then I run the playbook I have the following error

```bash 
TASK [geerlingguy.homebrew : Ensure configured homebrew packages are installed.] *******************************************************************************
failed: [localhost] (item=mysql) => {"ansible_loop_var": "item", "changed": false, "item": "mysql", "msg": "Error: The following directories are not writable by your user:\n/opt/homebrew\n\nYou should change the ownership of these directories to your user.\n  sudo chown -R $(whoami) /opt/homebrew\n\nAnd make sure that your user has write permission.\n  chmod u+w /opt/homebrew"}
```
