### ISSUE TITLE
Dock Command does not install correctly, causing the dock commands to skip

### ISSUE THREAD

**Issue by gregorskii** [geerlingguy/ansible-collection-mac#79]
I am finding that installing the fork of the brew package does not work on my machine as it seems to require the sudo password to link correctly. I have to remote desktop into the node uninstall the dockutil command and reinstall it with interactivity, when I do tha it prompts for my password and installs correctly.

Any ideas? Anyone experiencing this?

**Comment by supercoffee** [comment]
@gregorskii I think I've figured it out.  

When installing homebrew casks via the homebrew role, the sudo password is specified as an ansible variable. 
```yml
- name: Install configured cask applications.
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
        accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
        sudo_password: "{{ ansible_become_password | default(omit) }}"
      loop: "{{ homebrew_cask_apps }}"
      notify:
        - Clear homebrew cache
```

However, when using the dock role to install dockutil, no sudo password is specified.  

```yml
- name: Install dockutil.
  community.general.homebrew_cask:
    name: "{{ dockutil_homebrew_cask }}"
    state: present
  notify:
    - Clear homebrew cache
  when: dockutil_install
  tags: ['dock']

```

When I first attempt to run the playbook with dockutil tasks on a remote machine, it hangs on the install step (presumably waiting for a sudo password that never gets inputted. 
The second time I run the playbook, it skips over a bunch of items then fails with a cryptic permission error.


```
TASK [geerlingguy.mac.dock : See if TV is in the Dock.] *****************************************************************************************************************************************************************************
ok: [remote-mac.lan.example.com]

TASK [geerlingguy.mac.dock : Ensure Dock item TV is removed.] ***********************************************************************************************************************************************************************
skipping: [remote-mac.lan.example.com]

TASK [geerlingguy.mac.dock : Pause for 7 seconds between dock changes.] *************************************************************************************************************************************************************
skipping: [remote-mac.lan.example.com]

TASK [geerlingguy.mac.dock : Ensure required dock items exist.] *********************************************************************************************************************************************************************
included: /Users/myuser/.ansible/collections/ansible_collections/geerlingguy/mac/roles/dock/tasks/dock-add.yml for remote-mac.lan.example.com => (item={'name': 'Settings', 'path': '/Applications/System Settings.app/', 'pos': 2})
included: /Users/myuser/.ansible/collections/ansible_collections/geerlingguy/mac/roles/dock/tasks/dock-add.yml for remote-mac.lan.example.com => (item={'name': 'Firefox', 'path': '/Applications/Firefox.app/', 'pos': 3})
included: /Users/myuser/.ansible/collections/ansible_collections/geerlingguy/mac/roles/dock/tasks/dock-add.yml for remote-mac.lan.example.com => (item={'name': 'Firefox Developer Edition', 'path': '/Applications/Firefox Developer Edition.app/', 'pos': 4})
included: /Users/myuser/.ansible/collections/ansible_collections/geerlingguy/mac/roles/dock/tasks/dock-add.yml for remote-mac.lan.example.com => (item={'name': 'WebStorm', 'path': '/Applications/WebStorm.app/', 'pos': 5})
included: /Users/myuser/.ansible/collections/ansible_collections/geerlingguy/mac/roles/dock/tasks/dock-add.yml for remote-mac.lan.example.com => (item={'name': 'Datagrip', 'path': '/Applications/DataGrip.app/', 'pos': 7})
included: /Users/myuser/.ansible/collections/ansible_collections/geerlingguy/mac/roles/dock/tasks/dock-add.yml for remote-mac.lan.example.com => (item={'name': 'Iterm', 'path': '/Applications/Iterm.app/', 'pos': 8})
included: /Users/myuser/.ansible/collections/ansible_collections/geerlingguy/mac/roles/dock/tasks/dock-add.yml for remote-mac.lan.example.com => (item={'name': 'screenshots', 'path': '~/Pictures/screenshots/'})
included: /Users/myuser/.ansible/collections/ansible_collections/geerlingguy/mac/roles/dock/tasks/dock-add.yml for remote-mac.lan.example.com => (item={'name': 'Downloads', 'path': '~/Downloads/'})

TASK [geerlingguy.mac.dock : See if Dock item Settings exists.] *********************************************************************************************************************************************************************
ok: [remote-mac.lan.example.com]

TASK [geerlingguy.mac.dock : Get current dock section from output.] *****************************************************************************************************************************************************************
skipping: [remote-mac.lan.example.com]

TASK [geerlingguy.mac.dock : Ensure Dock item Settings exists.] *********************************************************************************************************************************************************************
fatal: [remote-mac.lan.example.com]: FAILED! => changed=false 
  cmd: dockutil --add '/Applications/System Settings.app/' --label Settings
  msg: '[Errno 13] Permission denied: b''dockutil'''
  rc: 13
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

When I log into the remote machine locally, I see that homebrew shows dockutil as installed, but running dockutil results in "command not found" indicating that homebrew didn't finish installing it.  (Presumably because the first run hung up on the sudo password step.) 

If I uninstall and reinstall dockutil on the machine locally and input the sudo password, then the dock role runs correctly. 

So, I think the workaround here is to install dockutil by adding it to `homebrew_cask_apps` installed by the homebrew role since that role correctly installs casks that require sudo. Also make sure to define `ansible_become_password` in your inventory ([see related issue](https://github.com/geerlingguy/ansible-collection-mac/issues/31))

**Comment by glennbrown** [comment]
Wanted to provide an update, I forked the repo and tried to add the sudo_password option and for the life of me I cannot get it to work. It either still prompts for the password even when specifying  --ask-become-pass, if I add ansible_become_password via a lookup it will install but it won't actually create the /usr/local/bin/dockutil entry.

However putting in the homebrew_cask_apps variable and running the homebrew role like @supercoffee said it works just fine.

**Comment by glennbrown** [comment]
Took a break and I came back and compared the homebrew code again and noticed there was a become option in the block that was being executed. I will submit a PR to fix that also includes a pause for dock position setting since I found it unreliable without it.

Original Code:
```yaml
- name: Install dockutil.
  community.general.homebrew_cask:
    name: "{{ dockutil_homebrew_cask }}"
    state: present
  notify:
    - Clear homebrew cache
  when: dockutil_install
  tags: ['dock']
```

Updated code
```yaml
- name: Install dockutil
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  community.general.homebrew_cask:
    name: "{{ dockutil_homebrew_cask }}"
    state: present
  notify:
    - Clear homebrew cache
  when: dockutil_install
  tags: ['dock']
```

I still don't fully understand why this works fine but it does.

**Comment by Kylmakalle** [comment]
It looks like pathfinding is a little different for Casks and normal brew utils. 
For remote systems, there's a common [flaw with the way macOS handles paths](https://gist.github.com/DrPsychick/847ea32c876fda2337e79096a8a23176). In short, ansible uses `/bin/sh` and macOS does not read **any startup files**. It will not read any files even with `/bin/bash/`
Back in 2021 I've encountered the same issue with **remote macs** and the easiest solution was **hardcoding the PATH**.

Today, I'm interested in **local setup** and I don't follow [geerlingguy/mac-dev-playbook](https://github.com/geerlingguy/mac-dev-playbook) where Jeff installs `dotfiles` with PATH first and then runs `dock` setup.

I've ended up with:
1. Installing [homebrew manually](https://github.com/Kylmakalle/dotfiles/blob/main/setup-brew.sh). Pre-installing homebrew also eliminates the Homebrew version check issue
- https://github.com/ansible-collections/community.general/issues/4708
- related to #92
2. Setting brew path before running dockutil, [appending `~/.zprofile`](https://github.com/Kylmakalle/dotfiles/blob/main/main.yml#L14-L25)
```yaml
- name: Ensure .zprofile exists
  copy:
    content: ""
    dest: "/Users/{{ lookup('env', 'USER') }}/.zprofile"
    force: no

- name: Ensure brew path in ~/.zprofile
  lineinfile:
    state: present
    path: "/Users/{{ lookup('env', 'USER') }}/.zprofile"
    line: eval "$({{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}/bin/brew shellenv)"
  tags: ['homebrew']
 ```
