### ISSUE TITLE
Support for spacers in the dock role

### ISSUE THREAD

**Issue by jbehrens94** [geerlingguy/ansible-collection-mac#81]
`dockutil` supports inserting 3 different kinds of spacers into the Dock. It would be nice to expand the dock role to be able to define spacers as well.

Currently, a `dockitems_persist.item[].path` value is needed for a dock item to be added. A spacer obviously can't have a path, nor a name. I'd suggest the following example:

```
dockitems_persist:
  - name: ''
    path: ''
    pos: 1
  - spacer:
      pos: 2
      type: 'small' (optional, no need to repeat `spacer` for a spacer type. Types can be `small` and `flex`).
```
